# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drone.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64rone.proto\"\x1e\n\x07Request\x12\x13\n\x0brequesttype\x18\x01 \x01(\x05\",\n\x10LocationResponse\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\"=\n\x13InsecticideResponse\x12\x12\n\nsuccessful\x18\x01 \x01(\x08\x12\x12\n\noutOfJuice\x18\x02 \x01(\x08\x62\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_LOCATIONRESPONSE = DESCRIPTOR.message_types_by_name['LocationResponse']
_INSECTICIDERESPONSE = DESCRIPTOR.message_types_by_name['InsecticideResponse']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'drone_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

LocationResponse = _reflection.GeneratedProtocolMessageType('LocationResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONRESPONSE,
  '__module__' : 'drone_pb2'
  # @@protoc_insertion_point(class_scope:LocationResponse)
  })
_sym_db.RegisterMessage(LocationResponse)

InsecticideResponse = _reflection.GeneratedProtocolMessageType('InsecticideResponse', (_message.Message,), {
  'DESCRIPTOR' : _INSECTICIDERESPONSE,
  '__module__' : 'drone_pb2'
  # @@protoc_insertion_point(class_scope:InsecticideResponse)
  })
_sym_db.RegisterMessage(InsecticideResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=15
  _REQUEST._serialized_end=45
  _LOCATIONRESPONSE._serialized_start=47
  _LOCATIONRESPONSE._serialized_end=91
  _INSECTICIDERESPONSE._serialized_start=93
  _INSECTICIDERESPONSE._serialized_end=154
# @@protoc_insertion_point(module_scope)
